// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/key_generator.dart';
import 'api/ssh.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'ssh/key_generator.dart';
import 'ssh/ssh_client.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.14.0-beta.2';

  @override
  int get rustContentHash => -1290137033;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_cliq',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateSshSshClientSftpConnectionAbsolute({
    required SftpConnection that,
    required String path,
  });

  Future<List<SftpName>> crateSshSshClientSftpConnectionListdir({
    required SftpConnection that,
    required String path,
  });

  Future<void> crateSshSshClientSftpConnectionMkdir({
    required SftpConnection that,
    required String path,
  });

  Future<SftpFileHandle> crateSshSshClientSftpConnectionOpenRead({
    required SftpConnection that,
    required String path,
  });

  Future<SftpFileHandle> crateSshSshClientSftpConnectionOpenWrite({
    required SftpConnection that,
    required String path,
    required bool truncate,
  });

  Future<Uint8List> crateSshSshClientSftpConnectionReadFileChunk({
    required SftpConnection that,
    required String path,
    required BigInt offset,
    required int maxBytes,
  });

  Future<void> crateSshSshClientSftpConnectionRemove({
    required SftpConnection that,
    required String path,
  });

  Future<void> crateSshSshClientSftpConnectionRename({
    required SftpConnection that,
    required String oldPath,
    required String newPath,
  });

  Future<void> crateSshSshClientSftpConnectionRmdir({
    required SftpConnection that,
    required String path,
  });

  Future<SftpFileAttr> crateSshSshClientSftpConnectionStat({
    required SftpConnection that,
    required String path,
  });

  Future<void> crateSshSshClientSftpConnectionWriteFileChunk({
    required SftpConnection that,
    required String path,
    required BigInt offset,
    required List<int> data,
    required bool truncate,
  });

  Future<Uint8List> crateSshSshClientSftpFileHandleReadChunk({
    required SftpFileHandle that,
    required int maxBytes,
  });

  Future<void> crateSshSshClientSftpFileHandleWriteChunk({
    required SftpFileHandle that,
    required List<int> data,
  });

  Stream<Uint8List> crateSshSshClientSshConnectionOutput({
    required SshConnection that,
  });

  Future<void> crateSshSshClientSshConnectionResize({
    required SshConnection that,
    required int columns,
    required int rows,
    required int pixelWidth,
    required int pixelHeight,
  });

  Future<void> crateSshSshClientSshConnectionWriteInput({
    required SshConnection that,
    required List<int> data,
  });

  Future<SftpConnection> crateApiSshConnectSftp({
    required String host,
    required int port,
    required String username,
    String? password,
    required List<String> privateKeys,
    required List<String?> keyPassphrases,
    Uint8List? expectedHostKey,
    required bool skipHostKeyVerification,
  });

  Future<SshConnection> crateApiSshConnectSsh({
    required String host,
    required int port,
    required String username,
    required int rows,
    required int columns,
    String? password,
    required List<String> privateKeys,
    required List<String?> keyPassphrases,
    Uint8List? expectedHostKey,
    required bool skipHostKeyVerification,
  });

  Future<GeneratedSshKey> crateApiKeyGeneratorGenerateSshKey({
    required SshKeyType keyType,
    String? comment,
    String? passphrase,
  });

  Future<void> crateApiInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SftpConnection;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SftpConnection;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SftpConnectionPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SftpFileHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SftpFileHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SftpFileHandlePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SshConnection;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SshConnection;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SshConnectionPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateSshSshClientSftpConnectionAbsolute({
    required SftpConnection that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateSshSshClientSftpConnectionAbsoluteConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSshSshClientSftpConnectionAbsoluteConstMeta =>
      const TaskConstMeta(
        debugName: "SftpConnection_absolute",
        argNames: ["that", "path"],
      );

  @override
  Future<List<SftpName>> crateSshSshClientSftpConnectionListdir({
    required SftpConnection that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_sftp_name,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateSshSshClientSftpConnectionListdirConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSshSshClientSftpConnectionListdirConstMeta =>
      const TaskConstMeta(
        debugName: "SftpConnection_listdir",
        argNames: ["that", "path"],
      );

  @override
  Future<void> crateSshSshClientSftpConnectionMkdir({
    required SftpConnection that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateSshSshClientSftpConnectionMkdirConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSshSshClientSftpConnectionMkdirConstMeta =>
      const TaskConstMeta(
        debugName: "SftpConnection_mkdir",
        argNames: ["that", "path"],
      );

  @override
  Future<SftpFileHandle> crateSshSshClientSftpConnectionOpenRead({
    required SftpConnection that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpFileHandle,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateSshSshClientSftpConnectionOpenReadConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSshSshClientSftpConnectionOpenReadConstMeta =>
      const TaskConstMeta(
        debugName: "SftpConnection_open_read",
        argNames: ["that", "path"],
      );

  @override
  Future<SftpFileHandle> crateSshSshClientSftpConnectionOpenWrite({
    required SftpConnection that,
    required String path,
    required bool truncate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          sse_encode_bool(truncate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpFileHandle,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateSshSshClientSftpConnectionOpenWriteConstMeta,
        argValues: [that, path, truncate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSshSshClientSftpConnectionOpenWriteConstMeta =>
      const TaskConstMeta(
        debugName: "SftpConnection_open_write",
        argNames: ["that", "path", "truncate"],
      );

  @override
  Future<Uint8List> crateSshSshClientSftpConnectionReadFileChunk({
    required SftpConnection that,
    required String path,
    required BigInt offset,
    required int maxBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          sse_encode_u_64(offset, serializer);
          sse_encode_u_32(maxBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateSshSshClientSftpConnectionReadFileChunkConstMeta,
        argValues: [that, path, offset, maxBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSshSshClientSftpConnectionReadFileChunkConstMeta =>
      const TaskConstMeta(
        debugName: "SftpConnection_read_file_chunk",
        argNames: ["that", "path", "offset", "maxBytes"],
      );

  @override
  Future<void> crateSshSshClientSftpConnectionRemove({
    required SftpConnection that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateSshSshClientSftpConnectionRemoveConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSshSshClientSftpConnectionRemoveConstMeta =>
      const TaskConstMeta(
        debugName: "SftpConnection_remove",
        argNames: ["that", "path"],
      );

  @override
  Future<void> crateSshSshClientSftpConnectionRename({
    required SftpConnection that,
    required String oldPath,
    required String newPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection(
            that,
            serializer,
          );
          sse_encode_String(oldPath, serializer);
          sse_encode_String(newPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateSshSshClientSftpConnectionRenameConstMeta,
        argValues: [that, oldPath, newPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSshSshClientSftpConnectionRenameConstMeta =>
      const TaskConstMeta(
        debugName: "SftpConnection_rename",
        argNames: ["that", "oldPath", "newPath"],
      );

  @override
  Future<void> crateSshSshClientSftpConnectionRmdir({
    required SftpConnection that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateSshSshClientSftpConnectionRmdirConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSshSshClientSftpConnectionRmdirConstMeta =>
      const TaskConstMeta(
        debugName: "SftpConnection_rmdir",
        argNames: ["that", "path"],
      );

  @override
  Future<SftpFileAttr> crateSshSshClientSftpConnectionStat({
    required SftpConnection that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sftp_file_attr,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateSshSshClientSftpConnectionStatConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSshSshClientSftpConnectionStatConstMeta =>
      const TaskConstMeta(
        debugName: "SftpConnection_stat",
        argNames: ["that", "path"],
      );

  @override
  Future<void> crateSshSshClientSftpConnectionWriteFileChunk({
    required SftpConnection that,
    required String path,
    required BigInt offset,
    required List<int> data,
    required bool truncate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          sse_encode_u_64(offset, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_bool(truncate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateSshSshClientSftpConnectionWriteFileChunkConstMeta,
        argValues: [that, path, offset, data, truncate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSshSshClientSftpConnectionWriteFileChunkConstMeta =>
      const TaskConstMeta(
        debugName: "SftpConnection_write_file_chunk",
        argNames: ["that", "path", "offset", "data", "truncate"],
      );

  @override
  Future<Uint8List> crateSshSshClientSftpFileHandleReadChunk({
    required SftpFileHandle that,
    required int maxBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpFileHandle(
            that,
            serializer,
          );
          sse_encode_u_32(maxBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateSshSshClientSftpFileHandleReadChunkConstMeta,
        argValues: [that, maxBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSshSshClientSftpFileHandleReadChunkConstMeta =>
      const TaskConstMeta(
        debugName: "SftpFileHandle_read_chunk",
        argNames: ["that", "maxBytes"],
      );

  @override
  Future<void> crateSshSshClientSftpFileHandleWriteChunk({
    required SftpFileHandle that,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpFileHandle(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateSshSshClientSftpFileHandleWriteChunkConstMeta,
        argValues: [that, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSshSshClientSftpFileHandleWriteChunkConstMeta =>
      const TaskConstMeta(
        debugName: "SftpFileHandle_write_chunk",
        argNames: ["that", "data"],
      );

  @override
  Stream<Uint8List> crateSshSshClientSshConnectionOutput({
    required SshConnection that,
  }) {
    final output = RustStreamSink<Uint8List>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
              that,
              serializer,
            );
            sse_encode_StreamSink_list_prim_u_8_strict_Sse(output, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 14,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateSshSshClientSshConnectionOutputConstMeta,
          argValues: [that, output],
          apiImpl: this,
        ),
      ),
    );
    return output.stream;
  }

  TaskConstMeta get kCrateSshSshClientSshConnectionOutputConstMeta =>
      const TaskConstMeta(
        debugName: "SshConnection_output",
        argNames: ["that", "output"],
      );

  @override
  Future<void> crateSshSshClientSshConnectionResize({
    required SshConnection that,
    required int columns,
    required int rows,
    required int pixelWidth,
    required int pixelHeight,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
            that,
            serializer,
          );
          sse_encode_u_32(columns, serializer);
          sse_encode_u_32(rows, serializer);
          sse_encode_u_32(pixelWidth, serializer);
          sse_encode_u_32(pixelHeight, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateSshSshClientSshConnectionResizeConstMeta,
        argValues: [that, columns, rows, pixelWidth, pixelHeight],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSshSshClientSshConnectionResizeConstMeta =>
      const TaskConstMeta(
        debugName: "SshConnection_resize",
        argNames: ["that", "columns", "rows", "pixelWidth", "pixelHeight"],
      );

  @override
  Future<void> crateSshSshClientSshConnectionWriteInput({
    required SshConnection that,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateSshSshClientSshConnectionWriteInputConstMeta,
        argValues: [that, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateSshSshClientSshConnectionWriteInputConstMeta =>
      const TaskConstMeta(
        debugName: "SshConnection_write_input",
        argNames: ["that", "data"],
      );

  @override
  Future<SftpConnection> crateApiSshConnectSftp({
    required String host,
    required int port,
    required String username,
    String? password,
    required List<String> privateKeys,
    required List<String?> keyPassphrases,
    Uint8List? expectedHostKey,
    required bool skipHostKeyVerification,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_String(username, serializer);
          sse_encode_opt_String(password, serializer);
          sse_encode_list_String(privateKeys, serializer);
          sse_encode_list_opt_String(keyPassphrases, serializer);
          sse_encode_opt_list_prim_u_8_strict(expectedHostKey, serializer);
          sse_encode_bool(skipHostKeyVerification, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSshConnectSftpConstMeta,
        argValues: [
          host,
          port,
          username,
          password,
          privateKeys,
          keyPassphrases,
          expectedHostKey,
          skipHostKeyVerification,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshConnectSftpConstMeta => const TaskConstMeta(
    debugName: "connect_sftp",
    argNames: [
      "host",
      "port",
      "username",
      "password",
      "privateKeys",
      "keyPassphrases",
      "expectedHostKey",
      "skipHostKeyVerification",
    ],
  );

  @override
  Future<SshConnection> crateApiSshConnectSsh({
    required String host,
    required int port,
    required String username,
    required int rows,
    required int columns,
    String? password,
    required List<String> privateKeys,
    required List<String?> keyPassphrases,
    Uint8List? expectedHostKey,
    required bool skipHostKeyVerification,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_String(username, serializer);
          sse_encode_u_32(rows, serializer);
          sse_encode_u_32(columns, serializer);
          sse_encode_opt_String(password, serializer);
          sse_encode_list_String(privateKeys, serializer);
          sse_encode_list_opt_String(keyPassphrases, serializer);
          sse_encode_opt_list_prim_u_8_strict(expectedHostKey, serializer);
          sse_encode_bool(skipHostKeyVerification, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSshConnectSshConstMeta,
        argValues: [
          host,
          port,
          username,
          rows,
          columns,
          password,
          privateKeys,
          keyPassphrases,
          expectedHostKey,
          skipHostKeyVerification,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshConnectSshConstMeta => const TaskConstMeta(
    debugName: "connect_ssh",
    argNames: [
      "host",
      "port",
      "username",
      "rows",
      "columns",
      "password",
      "privateKeys",
      "keyPassphrases",
      "expectedHostKey",
      "skipHostKeyVerification",
    ],
  );

  @override
  Future<GeneratedSshKey> crateApiKeyGeneratorGenerateSshKey({
    required SshKeyType keyType,
    String? comment,
    String? passphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_ssh_key_type(keyType, serializer);
          sse_encode_opt_String(comment, serializer);
          sse_encode_opt_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_generated_ssh_key,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKeyGeneratorGenerateSshKeyConstMeta,
        argValues: [keyType, comment, passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeyGeneratorGenerateSshKeyConstMeta =>
      const TaskConstMeta(
        debugName: "generate_ssh_key",
        argNames: ["keyType", "comment", "passphrase"],
      );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SftpConnection => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SftpConnection => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SftpFileHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpFileHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SftpFileHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpFileHandle;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SshConnection => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SshConnection => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(dcoDecodeString(raw));
  }

  @protected
  SftpConnection
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SftpConnectionImpl.frbInternalDcoDecode(dcoDecodeList(raw));
  }

  @protected
  SftpFileHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpFileHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SftpFileHandleImpl.frbInternalDcoDecode(dcoDecodeList(raw));
  }

  @protected
  SshConnection
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SshConnectionImpl.frbInternalDcoDecode(dcoDecodeList(raw));
  }

  @protected
  SshConnection
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SshConnectionImpl.frbInternalDcoDecode(dcoDecodeList(raw));
  }

  @protected
  SftpConnection
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SftpConnectionImpl.frbInternalDcoDecode(dcoDecodeList(raw));
  }

  @protected
  SftpFileHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpFileHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SftpFileHandleImpl.frbInternalDcoDecode(dcoDecodeList(raw));
  }

  @protected
  SshConnection
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SshConnectionImpl.frbInternalDcoDecode(dcoDecodeList(raw));
  }

  @protected
  SftpConnection
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SftpConnectionImpl.frbInternalDcoDecode(dcoDecodeList(raw));
  }

  @protected
  SftpFileHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpFileHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SftpFileHandleImpl.frbInternalDcoDecode(dcoDecodeList(raw));
  }

  @protected
  SshConnection
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SshConnectionImpl.frbInternalDcoDecode(dcoDecodeList(raw));
  }

  @protected
  RustStreamSink<Uint8List> dco_decode_StreamSink_list_prim_u_8_strict_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeString(raw);
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  SshKeyType dco_decode_box_autoadd_ssh_key_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ssh_key_type(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  EcdsaBits dco_decode_ecdsa_bits(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EcdsaBits.values[dcoDecodePrimitiveInt(raw)];
  }

  @protected
  GeneratedSshKey dco_decode_generated_ssh_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return GeneratedSshKey(
      privateKey: dco_decode_String(arr[0]),
      publicKey: dco_decode_String(arr[1]),
      fingerprint: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodePrimitiveInt(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeList(raw).map(dco_decode_String).toList();
  }

  @protected
  List<String?> dco_decode_list_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeList(raw).map(dco_decode_opt_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SftpName> dco_decode_list_sftp_name(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeList(raw).map(dco_decode_sftp_name).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  RsaBits dco_decode_rsa_bits(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RsaBits.values[dcoDecodePrimitiveInt(raw)];
  }

  @protected
  SftpFileAttr dco_decode_sftp_file_attr(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SftpFileAttr(
      size: dco_decode_opt_box_autoadd_u_64(arr[0]),
      mode: dco_decode_u_32(arr[1]),
      modifyTime: dco_decode_opt_box_autoadd_u_64(arr[2]),
      accessTime: dco_decode_opt_box_autoadd_u_64(arr[3]),
    );
  }

  @protected
  SftpName dco_decode_sftp_name(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SftpName(
      filename: dco_decode_String(arr[0]),
      longname: dco_decode_String(arr[1]),
      attr: dco_decode_sftp_file_attr(arr[2]),
    );
  }

  @protected
  SshKeyType dco_decode_ssh_key_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    switch (dcoDecodePrimitiveInt(arr[0])) {
      case 0:
        return SshKeyType_Ed25519();
      case 1:
        return SshKeyType_Ecdsa(dco_decode_ecdsa_bits(arr[1]));
      case 2:
        return SshKeyType_Rsa(dco_decode_rsa_bits(arr[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodePrimitiveInt(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodePrimitiveInt(raw);
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodePrimitiveInt(raw);
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  SftpConnection
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SftpConnectionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SftpFileHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpFileHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SftpFileHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SshConnection
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SshConnectionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SshConnection
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SshConnectionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SftpConnection
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SftpConnectionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SftpFileHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpFileHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SftpFileHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SshConnection
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SshConnectionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SftpConnection
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SftpConnectionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SftpFileHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpFileHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SftpFileHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SshConnection
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SshConnectionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<Uint8List> sse_decode_StreamSink_list_prim_u_8_strict_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  SshKeyType sse_decode_box_autoadd_ssh_key_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ssh_key_type(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  EcdsaBits sse_decode_ecdsa_bits(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return EcdsaBits.values[inner];
  }

  @protected
  GeneratedSshKey sse_decode_generated_ssh_key(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_privateKey = sse_decode_String(deserializer);
    var var_publicKey = sse_decode_String(deserializer);
    var var_fingerprint = sse_decode_String(deserializer);
    return GeneratedSshKey(
      privateKey: var_privateKey,
      publicKey: var_publicKey,
      fingerprint: var_fingerprint,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<String?> sse_decode_list_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String?>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_opt_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SftpName> sse_decode_list_sftp_name(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SftpName>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sftp_name(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RsaBits sse_decode_rsa_bits(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RsaBits.values[inner];
  }

  @protected
  SftpFileAttr sse_decode_sftp_file_attr(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_size = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_mode = sse_decode_u_32(deserializer);
    var var_modifyTime = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_accessTime = sse_decode_opt_box_autoadd_u_64(deserializer);
    return SftpFileAttr(
      size: var_size,
      mode: var_mode,
      modifyTime: var_modifyTime,
      accessTime: var_accessTime,
    );
  }

  @protected
  SftpName sse_decode_sftp_name(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_filename = sse_decode_String(deserializer);
    var var_longname = sse_decode_String(deserializer);
    var var_attr = sse_decode_sftp_file_attr(deserializer);
    return SftpName(
      filename: var_filename,
      longname: var_longname,
      attr: var_attr,
    );
  }

  @protected
  SshKeyType sse_decode_ssh_key_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return SshKeyType_Ed25519();
      case 1:
        var var_field0 = sse_decode_ecdsa_bits(deserializer);
        return SshKeyType_Ecdsa(var_field0);
      case 2:
        var var_field0 = sse_decode_rsa_bits(deserializer);
        return SshKeyType_Rsa(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection(
    SftpConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SftpConnectionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpFileHandle(
    SftpFileHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SftpFileHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    SshConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SshConnectionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    SshConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SshConnectionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection(
    SftpConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SftpConnectionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpFileHandle(
    SftpFileHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SftpFileHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    SshConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SshConnectionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpConnection(
    SftpConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SftpConnectionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSftpFileHandle(
    SftpFileHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SftpFileHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSshConnection(
    SshConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SshConnectionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_list_prim_u_8_strict_Sse(
    RustStreamSink<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_ssh_key_type(
    SshKeyType self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ssh_key_type(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_ecdsa_bits(EcdsaBits self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_generated_ssh_key(
    GeneratedSshKey self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.privateKey, serializer);
    sse_encode_String(self.publicKey, serializer);
    sse_encode_String(self.fingerprint, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_opt_String(
    List<String?> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_opt_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_sftp_name(
    List<SftpName> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sftp_name(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_rsa_bits(RsaBits self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_sftp_file_attr(SftpFileAttr self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_u_64(self.size, serializer);
    sse_encode_u_32(self.mode, serializer);
    sse_encode_opt_box_autoadd_u_64(self.modifyTime, serializer);
    sse_encode_opt_box_autoadd_u_64(self.accessTime, serializer);
  }

  @protected
  void sse_encode_sftp_name(SftpName self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.filename, serializer);
    sse_encode_String(self.longname, serializer);
    sse_encode_sftp_file_attr(self.attr, serializer);
  }

  @protected
  void sse_encode_ssh_key_type(SshKeyType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case SshKeyType_Ed25519():
        sse_encode_i_32(0, serializer);
      case SshKeyType_Ecdsa(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_ecdsa_bits(field0, serializer);
      case SshKeyType_Rsa(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_rsa_bits(field0, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class SftpConnectionImpl extends RustOpaque implements SftpConnection {
  // Not to be used by end users
  SftpConnectionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SftpConnectionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SftpConnection,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SftpConnection,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_SftpConnectionPtr,
  );

  Future<String> absolute({required String path}) => RustLib.instance.api
      .crateSshSshClientSftpConnectionAbsolute(that: this, path: path);

  Future<List<SftpName>> listdir({required String path}) => RustLib.instance.api
      .crateSshSshClientSftpConnectionListdir(that: this, path: path);

  Future<void> mkdir({required String path}) => RustLib.instance.api
      .crateSshSshClientSftpConnectionMkdir(that: this, path: path);

  Future<SftpFileHandle> openRead({required String path}) => RustLib
      .instance
      .api
      .crateSshSshClientSftpConnectionOpenRead(that: this, path: path);

  Future<SftpFileHandle> openWrite({
    required String path,
    required bool truncate,
  }) => RustLib.instance.api.crateSshSshClientSftpConnectionOpenWrite(
    that: this,
    path: path,
    truncate: truncate,
  );

  Future<Uint8List> readFileChunk({
    required String path,
    required BigInt offset,
    required int maxBytes,
  }) => RustLib.instance.api.crateSshSshClientSftpConnectionReadFileChunk(
    that: this,
    path: path,
    offset: offset,
    maxBytes: maxBytes,
  );

  Future<void> remove({required String path}) => RustLib.instance.api
      .crateSshSshClientSftpConnectionRemove(that: this, path: path);

  Future<void> rename({required String oldPath, required String newPath}) =>
      RustLib.instance.api.crateSshSshClientSftpConnectionRename(
        that: this,
        oldPath: oldPath,
        newPath: newPath,
      );

  Future<void> rmdir({required String path}) => RustLib.instance.api
      .crateSshSshClientSftpConnectionRmdir(that: this, path: path);

  Future<SftpFileAttr> stat({required String path}) => RustLib.instance.api
      .crateSshSshClientSftpConnectionStat(that: this, path: path);

  Future<void> writeFileChunk({
    required String path,
    required BigInt offset,
    required List<int> data,
    required bool truncate,
  }) => RustLib.instance.api.crateSshSshClientSftpConnectionWriteFileChunk(
    that: this,
    path: path,
    offset: offset,
    data: data,
    truncate: truncate,
  );
}

@sealed
class SftpFileHandleImpl extends RustOpaque implements SftpFileHandle {
  // Not to be used by end users
  SftpFileHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SftpFileHandleImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SftpFileHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SftpFileHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_SftpFileHandlePtr,
  );

  Future<Uint8List> readChunk({required int maxBytes}) => RustLib.instance.api
      .crateSshSshClientSftpFileHandleReadChunk(that: this, maxBytes: maxBytes);

  Future<void> writeChunk({required List<int> data}) => RustLib.instance.api
      .crateSshSshClientSftpFileHandleWriteChunk(that: this, data: data);
}

@sealed
class SshConnectionImpl extends RustOpaque implements SshConnection {
  // Not to be used by end users
  SshConnectionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SshConnectionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SshConnection,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SshConnection,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_SshConnectionPtr,
  );

  Stream<Uint8List> output() =>
      RustLib.instance.api.crateSshSshClientSshConnectionOutput(that: this);

  Future<void> resize({
    required int columns,
    required int rows,
    required int pixelWidth,
    required int pixelHeight,
  }) => RustLib.instance.api.crateSshSshClientSshConnectionResize(
    that: this,
    columns: columns,
    rows: rows,
    pixelWidth: pixelWidth,
    pixelHeight: pixelHeight,
  );

  Future<void> writeInput({required List<int> data}) => RustLib.instance.api
      .crateSshSshClientSshConnectionWriteInput(that: this, data: data);
}
