frontend:
  - changed-files:
      - any-glob-to-any-file: frontend/**

cliq_term:
  - changed-files:
      - any-glob-to-any-file: frontend/packages/cliq_term/**

backend:
  - changed-files:
      - any-glob-to-any-file: backend/**

docs:
  - changed-files:
      - any-glob-to-any-file: docs/**

repo:
  - changed-files:
      - any-glob-to-any-file: .github/**
