frontend:
  - changed-files:
      - any-glob-to-any-file: frontend/**

backend:
  - changed-files:
      - any-glob-to-any-file: backend/**

docs:
  - changed-files:
      - any-glob-to-any-file: docs/**

repo:
  - changed-files:
      - any-glob-to-any-file: .github/**
