ktlint:
  active: true

complexity:
  LongMethod:
    excludes:
      - '**/test/**'

style:
  UnusedImport:
    active: true
  ThrowsCount:
    active: false
  MaxLineLength:
    # This should be kept in sync with .editorconfig
    maxLineLength: 120
