name: cliq_ui
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.7"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: 0.21.3+1
  lucide_flutter: 0.548.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic

    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/IBMPlexMono/IBMPlexMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexMono/IBMPlexMono-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/IBMPlexMono/IBMPlexMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexMono/IBMPlexMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/IBMPlexMono/IBMPlexMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexMono/IBMPlexMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/IBMPlexMono/IBMPlexMono-Regular.ttf
        - asset: assets/fonts/IBMPlexMono/IBMPlexMono-Italic.ttf
          style: italic
        - asset: assets/fonts/IBMPlexMono/IBMPlexMono-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexMono/IBMPlexMono-LightItalic.ttf
          weight: 300
          style: italic
