// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import

import 'package:cliq/src/rust/frb_generated.dart';
import 'package:cliq/src/rust/ssh/key_generator.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generates a key pair of the given type with an optional comment.
/// If a passphrase is provided, the key will be encrypted.
Future<GeneratedSshKey> generateSshKey({
  required SshKeyType keyType,
  String? comment,
  String? passphrase,
}) => RustLib.instance.api.crateApiKeyGeneratorGenerateSshKey(
  keyType: keyType,
  comment: comment,
  passphrase: passphrase,
);
