// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import

import 'package:cliq/src/rust/frb_generated.dart';
import 'package:cliq/src/rust/ssh/ssh_client.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<SshConnection> connectSsh({
  required String host,
  required int port,
  required String username,
  required int rows,
  required int columns,
  String? password,
  String? privateKey,
}) => RustLib.instance.api.crateApiSshConnectSsh(
  host: host,
  port: port,
  username: username,
  rows: rows,
  columns: columns,
  password: password,
  privateKey: privateKey,
);
