# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
    desc "Push a new edge build to TestFlight"
    lane :edge do
        setup_ci if ENV['CI']

        app_store_connect_api_key(
            key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
            issuer_id: ENV['APP_STORE_CONNECT_API_ISSUER_ID'],
            key_content: ENV['APP_STORE_CONNECT_API_KEY_CONTENT'],
            is_key_content_base64: true
        )

        match(
            type: "appstore",
            platform: "macos",
            additional_cert_types: ["mac_installer_distribution"],
            readonly: true,
            git_basic_authorization: Base64.strict_encode64("jasonlessenich:#{ENV['MATCH_GIT_PAT']}")
        )

        update_code_signing_settings(
            use_automatic_signing: false,
            path: "Runner.xcodeproj",
            code_sign_identity: "Apple Distribution",
            bundle_identifier: "sh.cliq.cliq",
            profile_name: "match AppStore sh.cliq.cliq macos",
            team_id: ENV['APPLE_TEAM_ID']
        )

        build_app(
            workspace: "Runner.xcworkspace",
            scheme: "Runner",
            export_method: "app-store",
            export_team_id: ENV['APPLE_TEAM_ID']
        )
        upload_to_testflight(skip_waiting_for_build_processing: true)
    end
end
