// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: unused_import

import 'package:cliq/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'key_generator.freezed.dart';

/// Supported ECDSA curve sizes (in bits).
enum EcdsaBits { bits256, bits384, bits521 }

/// A generated SSH key pair in OpenSSH format.
class GeneratedSshKey {
  /// OpenSSH-formatted private key (PEM-like).
  final String privateKey;

  /// OpenSSH-formatted public key (`ssh-ed25519 AAAA... comment`).
  final String publicKey;

  /// SHA-256 fingerprint of the public key.
  final String fingerprint;

  const new({
    required this.privateKey,
    required this.publicKey,
    required this.fingerprint,
  });

  @override
  int get hashCode =>
      privateKey.hashCode ^ publicKey.hashCode ^ fingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GeneratedSshKey &&
          runtimeType == other.runtimeType &&
          privateKey == other.privateKey &&
          publicKey == other.publicKey &&
          fingerprint == other.fingerprint;
}

/// Supported RSA key sizes (in bits).
enum RsaBits { bits2048, bits4096 }

@freezed
sealed class SshKeyType with _$SshKeyType {
  const new _();

  const factory ed25519() = SshKeyType_Ed25519;
  const factory ecdsa(EcdsaBits field0) = SshKeyType_Ecdsa;
  const factory rsa(RsaBits field0) = SshKeyType_Rsa;
}
