// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: unused_import

import 'package:cliq/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SftpConnection>>
abstract class SftpConnection implements RustOpaqueInterface {
  Future<String> absolute({required String path});

  Future<List<SftpName>> listdir({required String path});

  Future<void> mkdir({required String path});

  Future<SftpFileHandle> openRead({required String path});

  Future<SftpFileHandle> openWrite({
    required String path,
    required bool truncate,
  });

  Future<Uint8List> readFileChunk({
    required String path,
    required BigInt offset,
    required int maxBytes,
  });

  Future<void> remove({required String path});

  Future<void> rename({required String oldPath, required String newPath});

  Future<void> rmdir({required String path});

  Future<SftpFileAttr> stat({required String path});

  Future<void> writeFileChunk({
    required String path,
    required BigInt offset,
    required List<int> data,
    required bool truncate,
  });
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SftpFileHandle>>
abstract class SftpFileHandle implements RustOpaqueInterface {
  Future<Uint8List> readChunk({required int maxBytes});

  Future<void> writeChunk({required List<int> data});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SshConnection>>
abstract class SshConnection implements RustOpaqueInterface {
  Stream<Uint8List> output();

  Future<void> resize({
    required int columns,
    required int rows,
    required int pixelWidth,
    required int pixelHeight,
  });

  Future<void> writeInput({required List<int> data});
}

class SftpFileAttr {
  final BigInt? size;
  final int mode;
  final BigInt? modifyTime;
  final BigInt? accessTime;

  const new({this.size, required this.mode, this.modifyTime, this.accessTime});

  @override
  int get hashCode =>
      size.hashCode ^ mode.hashCode ^ modifyTime.hashCode ^ accessTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SftpFileAttr &&
          runtimeType == other.runtimeType &&
          size == other.size &&
          mode == other.mode &&
          modifyTime == other.modifyTime &&
          accessTime == other.accessTime;
}

class SftpName {
  final String filename;
  final String longname;
  final SftpFileAttr attr;

  const new({
    required this.filename,
    required this.longname,
    required this.attr,
  });

  @override
  int get hashCode => filename.hashCode ^ longname.hashCode ^ attr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SftpName &&
          runtimeType == other.runtimeType &&
          filename == other.filename &&
          longname == other.longname &&
          attr == other.attr;
}
