// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: unused_import

import 'package:cliq/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SshConnection>>
abstract class SshConnection implements RustOpaqueInterface {
  Stream<Uint8List> output();

  Future<void> resize({
    required int columns,
    required int rows,
    required int pixelWidth,
    required int pixelHeight,
  });

  Future<void> writeInput({required List<int> data});
}
