# openssh server for testing
services:
  ssh-server:
    image: linuxserver/openssh-server:latest
    restart: unless-stopped
    ports:
      - "2222:2222"
    environment:
      # General
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      # SSH Server
      USER_NAME: ${USER_NAME}
      USER_PASSWORD: ${USER_PASSWORD}
      PASSWORD_ACCESS: ${PASSWORD_ACCESS}
      SUDO_ACCESS: ${SUDO_ACCESS}
      PUBLIC_KEY: ${PUBLIC_KEY}
