#!/usr/bin/env bash

# Set fast-fails
set -euo pipefail

# working dir preparation
WORK_DIR="$(pwd)"
cd "$(dirname "$0")"
# cd out of bin directory
cd ..

cd_into_work_dir() {
    cd "${WORK_DIR}"
}

trap cd_into_work_dir EXIT

echo "Installing environment file..."
cp --update=none .env.dist .env

echo "Starting docker containers..."
docker compose up -d --pull always

echo "Finished installation!"
