#!/usr/bin/env bash

# Set fast-fails
set -euo pipefail

# working dir preparation
WORK_DIR="$(pwd)"
cd "$(dirname "$0")"
# cd out of bin directory
cd ..

cd_into_work_dir() {
    cd "${WORK_DIR}"
}

trap cd_into_work_dir EXIT

echo "Installing environment file..."
cp --update=none .env.local.dist .env.local

echo "Shutting down any running docker containers..."
docker compose down --volumes --remove-orphans || true

echo "Pulling latest docker images..."
docker compose pull || true # We ignore failure here to allow offline usage

echo "Starting docker containers..."
docker compose up -d --wait

echo "Finished installation!"
