name: Backend Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Sets a default working directory
defaults:
  run:
    working-directory: ./backend  # Change the working directory to /backend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Install project
        run: bash ./app/install
      - name: Start Docker services
        run: docker compose up -d --wait
      - name: Run Gradle build
        run: ./gradlew build

# TODO: linting and formatting
