name: Backend Dependency Submission
on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

# Sets a default working directory
defaults:
  run:
    working-directory: ./backend # Change the working directory to /backend

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "25"
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v6
        with:
          cache-disabled: true
          build-root-directory: backend
          dependency-graph-exclude-configurations: '.*[Tt]est(Compile|Runtime)Classpath'
