name: Frontend Builds
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

# Sets a default working directory
defaults:
  run:
    working-directory: ./frontend  # Change the working directory to /frontend

# Limits the permissions for the actions
permissions:
  contents: read

jobs:
  # iOS Build
  build-ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - &get-flutter-dependencies
        name: Get dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign

  # Android Build
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - *get-flutter-dependencies

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build Android App Bundle
        run: flutter build appbundle --release

  # Windows Build (x64 and ARM64)
  build-windows:
    name: Build Windows
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            runner: windows-latest
            flutter-channel: stable
          - arch: arm64
            runner: windows-11-arm
            flutter-channel: main # Remove when https://github.com/subosito/flutter-action/issues/345
    steps:
      - uses: actions/checkout@v6

      - name: Install Inno Setup
        run: winget install --id JRSoftware.InnoSetup -e --silent

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter-channel }}
          cache: true

      - &install-fastforge
        name: Install fastforge
        run: dart pub global activate fastforge

      - *get-flutter-dependencies

      - name: Build Windows Installer (${{ matrix.arch }})
        run: fastforge package --platform windows --targets exe

      - name: Rename MSIX
        run: mv dist/**/*.exe dist/cliqsetup-windows-${{ matrix.arch }}.exe

      - name: Upload Windows installer artifacts
        uses: actions/upload-artifact@v7
        with:
          name: windows-${{ matrix.arch }}-installer
          path: frontend/dist/cliqsetup-windows-${{ matrix.arch }}.exe
          archive: false
          if-no-files-found: error

  # macOS Build (No need to separate out ARM64 flutter builds dual arch by default)
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: npm install -g appdmg

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - *install-fastforge
      - *get-flutter-dependencies

      - name: Build macOS Installer
        run: fastforge package --platform macos --targets dmg

      - name: Rename DMG
        run: mv dist/**/*.dmg dist/cliq.dmg

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v7
        with:
          name: macos-installer
          path: frontend/dist/cliq.dmg
          archive: false
          if-no-files-found: error

  # Linux Build (x64 and ARM64)
  build-linux:
    name: Build Linux
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            runner: ubuntu-latest
            flutter-channel: stable
            appimagetool-name: appimagetool-x86_64.AppImage
          - arch: arm64
            runner: ubuntu-24.04-arm
            flutter-channel: main # Remove when https://github.com/subosito/flutter-action/issues/345
            appimagetool-name: appimagetool-aarch64.AppImage
    steps:
      - uses: actions/checkout@v6

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            locate \
            pkg-config \
            libgtk-3-dev \
            libglib2.0-0 \
            libglib2.0-dev \
            libx11-dev \
            libxext-dev \
            libxinerama-dev \
            libxrandr-dev \
            libxrender-dev \
            yasm \
            libglu1-mesa \
            libglu1-mesa-dev

      - name: Install appimagetool
        run: |
          wget -O appimagetool "https://github.com/AppImage/appimagetool/releases/download/continuous/${{ matrix.appimagetool-name }}"
          chmod +x appimagetool
          sudo mv appimagetool /usr/local/bin/

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter-channel }}
          cache: true

      - *install-fastforge
      - *get-flutter-dependencies

      - name: Build Linux AppImage
        run: fastforge package --platform linux --targets appimage

      - name: Rename AppImage
        run: mv dist/**/*.AppImage dist/cliq-${{ matrix.arch }}.AppImage

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v7
        with:
          name: linux-${{ matrix.arch }}-installer
          path: frontend/dist/cliq-${{ matrix.arch }}.AppImage
          archive: false
          if-no-files-found: error
